substitutions:
  # Settings - Editable values
  device_name: "nspanel-soggiorno"
  friendly_name: "NSPanel Soggiorno"
  wifi_ssid: !secret wifi_ssid_casa
  wifi_password: !secret wifi_password_casa
  #nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  ## Add-on climate
  heater_relay: "1"     
  temp_units: "째C"      # Temperatures in Fahrenheit
  temp_min: "15"        # Min supported temperature is 40째F
  temp_max: "25"        # Max supported temperature is 80째F
  temp_step: "0.1"        # Temperature granularity is 1째F
  heat_deadband: "0.3"  # Temperature delta before engaging heat
  heat_overrun: "0.3"   # Temperature delta before disengaging heat

esphome:
  name: "nspanel-soggiorno"
  friendly_name: "nspanel-soggiorno"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxx"

captive_portal:



# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
